fngs/analyze/urls.py
from django.conf.urls import url
from . import views


app_name = 'analyze'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<dataset_id>[\w\-]+)/$', views.dataset, name='dataset'),
    url(r'dataset/add/$', views.create_dataset, name='dataset-add'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/delete/$', views.delete_dataset, name='dataset-delete'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/subject/add/$', views.create_subject, name='subject-add'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/delete/$', views.delete_subject, name='subject-delete'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/analyze/$', views.analyze_subject, name='subject-analyze'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/results/$', views.get_results, name='subject-results'),
]

fngs/fngs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^analyze/', include('analyze.urls')),
    url(r'^explore/', include('explore.urls')),
    url(r'^algorithms/', include('algorithms.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
    urlpatterns += static(settings.OUTPUT_DIR, document_root = settings.OUTPUT_DIR)

fngs/analyze/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
import os.path as op
import os
import uuid


def get_func_file_path(instance, filename):
	# extension is everything after first period
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "func", filename]))
def get_anat_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "anat", filename]))

def get_dti_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "dti", filename]))

def get_mprage_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "mprage", filename]))

def get_bvals_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "bvals", filename]))

def get_bvecs_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "bvecs", filename]))

class Dataset(models.Model):
	dataset_id = models.CharField(max_length=30)
	collection_site = models.CharField(max_length=40)
	output_url = models.CharField(max_length=200, null=True, blank=True)

	def add_output_url(self, url):
		output_url = models.TextField(url)
			
	def __str__(self):
		return str(self.dataset_id)

	def __eq__(self, other):
		if isinstance(other, self.__class__):
			return self.dataset_id == other.dataset_id
		return False

	def __ne__(self, other):
		return not self.__eq__(other)


class Subject(models.Model):
	dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
	sub_id = models.CharField(max_length=30)
	sess_id = models.CharField(max_length=30)
	struct_scan = models.FileField(upload_to=get_anat_file_path, null=True, blank=True)
	func_scan = models.FileField(upload_to=get_func_file_path, null=True, blank=True)
	output_url = models.CharField(max_length=200, null=True, blank=True)
	STC_CHOICES = (
		(None, 'None'),
		('up', 'Bottom Up Acquisition (standard)'),
		('down', 'Top Down Acquisition'),
		("interleaved", 'Interleaved Acquisition')
	)
	slice_timing = models.CharField(max_length=20, choices=STC_CHOICES)
	AN_CHOICES = (
		(1, 'T1w'),
		(2, 'T2w'),
		(3, 'PD')
	)
	an = models.IntegerField(choices=AN_CHOICES, default=1)
        dti_file = models.FileField(upload_to=get_dti_file_path, null=True, blank=True)
        mprage_file = models.FileField(upload_to=get_mprage_file_path, null=True, blank=True)
        bvals_file = models.FileField(upload_to=get_bvals_file_path, null=True, blank=True)
        bvecs_file = models.FileField(upload_to=get_bvecs_file_path, null=True, blank=True)

	def __eq__(self, other):
		if isinstance(other, self.__class__):
			return ((self.dataset == other.dataset) and (self.sub_id == other.sub_id))
		return False

	def get_id(self):
		return str(op.splitext(op.splitext(op.basename(self.func_scan.name))[0])[0])

	def __ne__(self, other):
		return not self.__eq__(other)

	def add_output_url(self, url):
		output_url = models.TextField(url)

	def __str__(self):
		return str(str(self.dataset) + "_" + str(self.sub_id))

fngs/analyze/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Dataset, Subject
from django.utils.translation import ugettext_lazy as _


class DatasetForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['dataset_id', 'collection_site']
        labels={
        	'dataset': _('Dataset'),
        	'collection_site':_('Collection Site')
        }
        help_texts={
        	'dataset': _('The name of the dataset this subject is a part of.'),
        	'collection_site':_('The location the dataset was collected.')
        }

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['dataset', 'sub_id', 'sess_id', 'func_scan', 'struct_scan','an', 'slice_timing', 'dti_file', 'mprage_file', 'bvals_file', 'bvecs_file']
        labels={
        	'dataset': _('Dataset'),
        	'sub_id': _('Subject ID'),
        	'sess_id': _('Session ID'),
        	'func_scan':_('Functional Scan'),
        	'struct_scan':_('Structural Scan'),
        	'an':_('Structural scan type'),
        	'slice_timing':_('Slice Timing Method'),
            'dti_file':_('DTI Image'),
            'mprage_file':_('MPRAGE Image'),
            'bvals_file':_('DTI b-values File'),
            'bvecs_file':_('DTI b-vectors File')
        }
        help_texts={
        	'dataset': _('The name of the dataset this subject is a part of.'),
        	'sub_id': _('A unique identifier for the subject.'),
        	'sess_id': _('A session name for the subject.'),
        	'func_scan':_('the fMRI of this subject.'),
        	'struct_scan':_('the structural MRI of this subject.'),
        	'an':_('The Type of structural scan.'),
        	'slice_timing':_('The method in which slices were acquired.'),
            'dti_file':_('DTI image file for NDMG pipeline'),
            'mprage_file':_('MPRAGE image file for NDMG pipeline'),
            'bvals_file':_('DTI b-values file for NDMG pipeline'),
            'bvecs_file':_('DRI b-vectors file for NDMG pipeline')
        }

fngs/analyze/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Dataset, Subject
from .forms import DatasetForm, SubjectForm
from ndmg.scripts.fngs_pipeline import fngs_pipeline
from ndmg.scripts.ndmg_pipeline import ndmg_pipeline
from django.conf import settings
import time
from ndmg.utils import utils as mgu
from threading import Thread
from multiprocessing import Process
import os
import re


BRAIN_FILE_TYPES = ['nii', 'nii.gz']

def index(request):
	datasets = Dataset.objects.all()
	return render(request, 'analyze/index.html', {'datasets': datasets})


def dataset(request, dataset_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	return render(request, 'analyze/dataset.html', {'dataset': dataset})

def create_dataset(request):
	form = DatasetForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		for dataset in Dataset.objects.all():
			if dataset.dataset_id == form.cleaned_data.get("dataset_id"):
				context = {
					'dataset': dataset,
					'error_message': 'You already added that dataset.',
				}
				return render(request, 'analyze/create_dataset.html', context)
		dataset = form.save(commit=False)
		dataset.output_url = str(settings.OUTPUT_DIR + dataset.dataset_id)
		mgu().execute_cmd("mkdir -p " + str(dataset.output_url))
		dataset.save()
		return render(request, 'analyze/dataset.html', {'dataset': dataset})
	context = {
		"form": form,
	}
	return render(request, 'analyze/create_dataset.html', context)

def create_subject(request, dataset_id):
	form = SubjectForm(request.POST or None, request.FILES or None)
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	if form.is_valid():
		dataset_subs = dataset.subject_set.all()
		for sub in dataset_subs:
			if sub.sub_id == form.cleaned_data.get("sub_id"):
				context = {
					'dataset': dataset,
					'form': form,
					'error_message': 'You already added that subject',
				}
				return render(request, 'analyze/create_subject.html', context)
		subject = form.save(commit=False)
		subject.dataset = dataset
		subject.struct_scan = request.FILES['struct_scan']
		file_type = subject.struct_scan.url.split('.', 1)[-1]
		file_type = file_type.lower()
		print(file_type)
		if file_type not in BRAIN_FILE_TYPES:
			context = {
				'album': dataset,
				'form': form,
				'error_message': 'Brain File must be .nii or .nii.gz',
			}
			return render(request, 'analyze/create_subject.html', context)
		subject.func_scan = request.FILES['func_scan']
		file_type = subject.func_scan.url.split('.', 1)[-1]
		file_type = file_type.lower()
		if file_type not in BRAIN_FILE_TYPES:
			context = {
				'dataset': dataset,
				'form': form,
				'error_message': 'Brain File must be .nii or .nii.gz',
			}
			return render(request, 'analyze/create_subject.html', context)
                
                subject.dti_file = request.FILES['dti_file']
                subject.mprage_file = request.FILES['mprage_file']
                subject.bvals_file = request.FILES['bvals_file']
                subject.bvecs_file = request.FILES['bvecs_file']
		print subject.func_scan.url
		subject.save()
		return render(request, 'analyze/dataset.html', {'dataset': dataset})
	context = {
		"form": form,
	}
	return render(request, 'analyze/create_subject.html', context)

def analysis(dataset, sub_id, output_dir):
	subject = get_object_or_404(Subject, dataset=dataset, sub_id=sub_id)
	subject.output_url = output_dir
	fngs_pipeline(subject.func_scan.url, subject.struct_scan.url, subject.an,
			      settings.AT_FOLDER + '/atlas/MNI152_T1_2mm.nii.gz', settings.AT_FOLDER + '/atlas/MNI152_T1_2mm_brain.nii.gz',
			      settings.AT_FOLDER + '/mask/MNI152_T1_2mm_brain_mask.nii.gz', settings.AT_FOLDER + '/mask/HarvOx_lv_thr25_2mm.nii.gz', 
			      [settings.AT_FOLDER + '/label/desikan_2mm.nii.gz'], output_dir, stc=subject.slice_timing, fmt='graphml')

        ndmg_pipeline(subject.dti_file.url, subject.bvals_file.url, subject.bvecs_file.url, subject.mprage_file.url, settings.AT_FOLDER + '/atlas/MNI152_T1_2mm.nii.gz', settings.AT_FOLDER + '/mask/MNI152_T1_2mm_brain_mask.nii.gz', [settings.AT_FOLDER + '/label/desikan_2mm.nii.gz'], output_dir + "/ndmg_results")

        #ndmg_run_cmd = "ndmg_pipeline " + str(subject.dti_file.url) + " " + str(subject.bvals_file.url) + " " + str(subject.bvecs_file.url) + " " + str(subject.mprage_file.url) + " " + str(settings.AT_FOLDER + '/atlas/MNI152_T1_2mm.nii.gz') + " " + str(settings.AT_FOLDER + '/mask/MNI152_T1_2mm_brain_mask.nii.gz') + " " + output_dir + "/ndmg_results " + str(settings.AT_FOLDER + '/label/desikan_2mm.nii.gz')
        #mgu().execute_cmd(ndmg_run_cmd)

        ndmg_bids_cmd = "ndmg_bids " + output_dir + "/ndmg_results/graphs/ " + output_dir + "/ndmg_results/qc group"
        mgu().execute_cmd(ndmg_bids_cmd)
        
	wd = os.getcwd()
	# go to where the subject is
	os.chdir(dataset.output_url)
	sub_folder = re.split('/', subject.output_url)[-1]

	mgu().execute_cmd('zip -r ' + str(sub_folder) + ".zip " + str(sub_folder))
	# change directory back
	os.chdir(wd)
	# and update the subject
	subject.save() # updated the output location, so save the updated subject

def analyze_subject(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset=dataset, sub_id=sub_id)
	try:
		# update subject save location
		if subject.output_url is not None:
			mgu().execute_cmd("rm -rf " + subject.output_url)
		subject.output_url = None
		subject.save()
		date = time.strftime("%d-%m-%Y")
		output_dir = settings.OUTPUT_DIR + dataset_id + "/" + sub_id + "_" + date
		p = Process(target=analysis, args=(dataset, sub_id, output_dir,))
		p.daemon=True
		p.start()
	except:
		raise Http404
	return render(request, 'analyze/dataset.html', {'dataset':dataset})

def get_results(request, dataset_id, sub_id):
	pass

def delete_dataset(request, dataset_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	# get the subjects of this dataset to delete all of them
	try:
		subjects = Subject.objects.get(dataset=dataset)
	except Subject.DoesNotExist:
		subjects=None
	if subjects:
		return HttpResponse("There are subjects in here!", status=404)
	else:
		dataset.delete()
		datasets = Dataset.objects.all()
		return render(request, 'analyze/index.html', {'datasets': datasets})


def delete_subject(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset=dataset, sub_id=sub_id)
	# clear all traces of the subject from our storage system
	mgu().execute_cmd("rm -rf " + subject.func_scan.url)
	mgu().execute_cmd("rm -rf " + subject.struct_scan.url)
	if subject.output_url is not None:
		mgu().execute_cmd("rm -rf " + subject.output_url)
	subject.delete()
	datasets = Dataset.objects.all()
	return render(request, 'analyze/dataset.html', {'dataset': dataset})

fngs/analyze/templates/analyze/create_dataset.html
{% extends 'home/base.html' %}

{% block body %}
	<div class="container-fluid">

		<div class="row">

        	<div class="box">
				<div class="col-sm-12 col-md-7">
					<div class panel panel-default">
						<div class="panel-body">
							<div class="row">
	        					<div class="box">
									<h3>Add a New Dataset</h3>
									<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
										{% csrf_token %}
										{% if error_message %}
				                        	<p><strong>{{ error_message }}</strong></p>
				                    	{% endif %}
	        							{% include 'analyze/form-template.html' %}
										<div class = "form-group">
											<div class="col-sm-offset-2 col-sm-10">
												<button type="submit" class="btn btn-success">Add Dataset</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

fngs/analyze/templates/analyze/create_subject.html
{% extends 'home/base.html' %}

{% block body %}
	<div class="container-fluid">

		<div class="row">

        	<div class="box">
				<div class="col-sm-12 col-md-7">
					<div class panel panel-default">
						<div class="panel-body">
							<div class="row">
	        					<div class="box">
									<h3>Add a New Subject</h3>
									<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
										{% csrf_token %}
										{% if error_message %}
				                        	<p><strong>{{ error_message }}</strong></p>
				                    	{% endif %}
	        							{% include 'analyze/form-template.html' %}
										<div class = "form-group">
											<div class="col-sm-offset-2 col-sm-10">
												<button type="submit" class="btn btn-success">Add Subject</button>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

fngs/analyze/templates/analyze/dataset.html
{% extends 'home/base.html' %}

{% block body %}
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h1 class="intro-text text-center">Upload Data</h1>
                <hr>
                <hr class="visible-xs">
                <p>Dataset: {{ dataset }}</p> 
                <p>Collection Site: {{ dataset.collection_site }}</p>  

                <table class="table">
                        <thead>
                        <tr>
                            <th>Subject ID</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for subject in dataset.subject_set.all %}
                            <tr>
                                <td>{{ subject.sub_id }}</td>
                                <td>
                                    <form action="{% url 'analyze:subject-analyze' dataset.dataset_id subject.sub_id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Analyze
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url 'analyze:subject-delete' dataset.dataset_id subject.sub_id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                <form class="form-horizontal" action="{% url 'analyze:subject-add' dataset.dataset_id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class = "form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="add" class="btn btn-success">Add Subject</button>
                        </div>
                    </div>    
                </form>
                <form class="form-horizontal" action="{% url 'analyze:dataset-delete' dataset.dataset_id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class = "form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="delete" class="btn btn-danger">Delete Dataset</button>
                        </div>
                    </div>         
                </form>

            </div>
        </div>
    </div>
{% endblock %}

fngs/analyze/templates/analyze/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

fngs/analyze/templates/analyze/index.html
{% extends 'home/base.html' %}

{% block body %}
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h1 class="intro-text text-center">Upload Data</h1>
                <hr>
                <hr class="visible-xs">
                {% if datasets %}
                <ul>
                    {% for dataset in datasets %}
                    <li><a href="{% url 'analyze:dataset' dataset.dataset_id %}">{{ dataset.dataset_id }}</a></li>
                    {% endfor %}                    
                </ul>
                {% else %}
                <h3>No Datasets Available for Public Viewing.</h3>
                {% endif %}
                <form class="form-horizontal" action="{% url 'analyze:dataset-add' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class = "form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="delete" class="btn btn-success">Add Dataset</button>
                        </div>
                    </div>         
                </form>
            </div>
        </div>
    </div>
{% endblock %}