fngs/algorithms/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'algorithms'

urlpatterns = [
	# /explore/
    url(r'^$', views.index, name='index'),
]

fngs/analyze/urls.py
from django.conf.urls import url
from . import views


app_name = 'analyze'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<dataset_id>[\w\-]+)/$', views.dataset, name='dataset'),
    url(r'dataset/add/$', views.create_dataset, name='dataset-add'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/delete/$', views.delete_dataset, name='dataset-delete'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/subject/add/$', views.create_subject, name='subject-add'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/delete/$', views.delete_subject, name='subject-delete'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/analyze/$', views.analyze_subject, name='subject-analyze'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/results/$', views.get_results, name='subject-results'),
]

fngs/explore/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'explore'

urlpatterns = [
	# /explore/
    url(r'^$', views.index, name='index'),
    # /explore/<dataset_id>/
    url(r'^(?P<dataset_id>[\w\-]+)/$', views.dataset, name='dataset'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/download/$', views.download_subject, name='subject-download'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/overall/$', views.sub_overall_qc, name='sub-qc-overall'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/motion/$', views.sub_motion_qc, name='sub-qc-motion'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/register/$', views.sub_register_qc, name='sub-qc-register'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/stats/$', views.sub_stats_qc, name='sub-qc-stats'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/nuisance/$', views.sub_nuisance_qc, name='sub-qc-nuisance'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/timeseries/$', views.sub_timeseries_qc, name='sub-qc-timeseries'),
]

fngs/fngs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^analyze/', include('analyze.urls')),
    url(r'^explore/', include('explore.urls')),
    url(r'^algorithms/', include('algorithms.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
    urlpatterns += static(settings.OUTPUT_DIR, document_root = settings.OUTPUT_DIR)

fngs/home/urls.py
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [
	# /explore/
    url(r'^$', views.index, name='index')
    # /explore/<dataset_id>/
]

fngs/home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">

{% load staticfiles %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FNGS - Functional Neurodata Graphs Service</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/business-casual.css' %}">

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Functional Neurodata Graphs Service</div>
    <div class="address-bar">A One-Click Pipeline for the Efficient and Robust Acquisition of fMRI Connectomes</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{% url 'home:index' %}">FNGS</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'home:index' %}">Home</a>
                    </li>
                                        <li>
                        <a href="{% url 'analyze:index' %}">Analyze</a>
                    </li>
                     <li>
                        <a href="{% url 'explore:index' %}">Explore</a>
                    </li>
                     <li>
                        <a href="{% url 'algorithms:index' %}">Algorithms</a>
                    </li>
               </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block body %}
    {% endblock %}
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Neurodata 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>