fngs/explore/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'explore'

urlpatterns = [
	# /explore/
    url(r'^$', views.index, name='index'),
    # /explore/<dataset_id>/
    url(r'^(?P<dataset_id>[\w\-]+)/$', views.dataset, name='dataset'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/download/$', views.download_subject, name='subject-download'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/overall/$', views.sub_overall_qc, name='sub-qc-overall'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/motion/$', views.sub_motion_qc, name='sub-qc-motion'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/register/$', views.sub_register_qc, name='sub-qc-register'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/stats/$', views.sub_stats_qc, name='sub-qc-stats'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/nuisance/$', views.sub_nuisance_qc, name='sub-qc-nuisance'),
    url(r'dataset/(?P<dataset_id>[\w\-]+)/(?P<sub_id>[\w\-]+)/timeseries/$', views.sub_timeseries_qc, name='sub-qc-timeseries'),
]

fngs/fngs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^analyze/', include('analyze.urls')),
    url(r'^explore/', include('explore.urls')),
    url(r'^algorithms/', include('algorithms.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
    urlpatterns += static(settings.OUTPUT_DIR, document_root = settings.OUTPUT_DIR)

fngs/home/urls.py
from django.conf.urls import url
from . import views


app_name = 'home'

urlpatterns = [
	# /explore/
    url(r'^$', views.index, name='index')
    # /explore/<dataset_id>/
]

fngs/analyze/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
import os.path as op
import os
import uuid


def get_func_file_path(instance, filename):
	# extension is everything after first period
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "func", filename]))
def get_anat_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "anat", filename]))

def get_dti_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "dti", filename]))

def get_mprage_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "mprage", filename]))

def get_bvals_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "bvals", filename]))

def get_bvecs_file_path(instance, filename):
    return os.path.join("/".join([str(instance.dataset), str(instance.sub_id), str(instance.sess_id), "bvecs", filename]))

class Dataset(models.Model):
	dataset_id = models.CharField(max_length=30)
	collection_site = models.CharField(max_length=40)
	output_url = models.CharField(max_length=200, null=True, blank=True)

	def add_output_url(self, url):
		output_url = models.TextField(url)
			
	def __str__(self):
		return str(self.dataset_id)

	def __eq__(self, other):
		if isinstance(other, self.__class__):
			return self.dataset_id == other.dataset_id
		return False

	def __ne__(self, other):
		return not self.__eq__(other)


class Subject(models.Model):
	dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
	sub_id = models.CharField(max_length=30)
	sess_id = models.CharField(max_length=30)
	struct_scan = models.FileField(upload_to=get_anat_file_path, null=True, blank=True)
	func_scan = models.FileField(upload_to=get_func_file_path, null=True, blank=True)
	output_url = models.CharField(max_length=200, null=True, blank=True)
	STC_CHOICES = (
		(None, 'None'),
		('up', 'Bottom Up Acquisition (standard)'),
		('down', 'Top Down Acquisition'),
		("interleaved", 'Interleaved Acquisition')
	)
	slice_timing = models.CharField(max_length=20, choices=STC_CHOICES)
	AN_CHOICES = (
		(1, 'T1w'),
		(2, 'T2w'),
		(3, 'PD')
	)
	an = models.IntegerField(choices=AN_CHOICES, default=1)
        dti_file = models.FileField(upload_to=get_dti_file_path, null=True, blank=True)
        mprage_file = models.FileField(upload_to=get_mprage_file_path, null=True, blank=True)
        bvals_file = models.FileField(upload_to=get_bvals_file_path, null=True, blank=True)
        bvecs_file = models.FileField(upload_to=get_bvecs_file_path, null=True, blank=True)

	def __eq__(self, other):
		if isinstance(other, self.__class__):
			return ((self.dataset == other.dataset) and (self.sub_id == other.sub_id))
		return False

	def get_id(self):
		return str(op.splitext(op.splitext(op.basename(self.func_scan.name))[0])[0])

	def __ne__(self, other):
		return not self.__eq__(other)

	def add_output_url(self, url):
		output_url = models.TextField(url)

	def __str__(self):
		return str(str(self.dataset) + "_" + str(self.sub_id))

fngs/explore/models.py
from __future__ import unicode_literals

fngs/explore/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.views import generic
from analyze.models import Dataset, Subject
import os
from ndmg.utils import utils as mgu
import nibabel as nb

def index(request):
	datasets = Dataset.objects.all()
	return render(request, 'explore/index.html', {'datasets': datasets})

def dataset(request, dataset_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	return render(request, 'explore/dataset.html', {'dataset': dataset})

def download_subject(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	## TODO: handle this better here; don't just return the same page
	if subject.output_url is not None:
		file_path = subject.output_url + ".zip"
		if os.path.exists(file_path):
			with open(file_path, 'rb') as fh:
				response = HttpResponse(fh.read(), content_type='application/zip')
				response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
				return response
		else:
			raise Http404
	return render(request, 'explore/dataset.html', {'dataset': dataset})

def sub_overall_qc(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	if subject.output_url is not None:
		scan = nb.load(subject.func_scan.url)
		res = scan.header.get_zooms()
		context = {'dataset': dataset,
				   'subject': subject,
				   'res': res[0:3],
				   'tr': res[3]
		}
		return render(request, 'explore/overall.html', context)
	else:
		raise Http404("Either the subject is currently being analyzed, or you have not analyzed this subject yet.")

def sub_motion_qc(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	test = mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*trans*\"")[0].rstrip('\n')
	context = {'dataset': dataset,
			   'subject': subject,
			   'trans': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*trans*\"")[0].rstrip('\n'),
			   'rot': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*rot*\"")[0].rstrip('\n'),
			   'disp': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*disp*\"")[0].rstrip('\n'),
			   'mcjitter':mgu().execute_cmd("find " + subject.output_url + " -wholename \"*mc*" + subject.get_id() + "*jitter*\"")[0].rstrip('\n'),
			   'mckde':mgu().execute_cmd("find " + subject.output_url + " -wholename \"*mc*" + subject.get_id() + "*kde*\"")[0].rstrip('\n')}
	return render(request, 'explore/motion.html', context)

def sub_stats_qc(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	context = {'dataset': dataset,
			   'subject': subject,
			   'std': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*std*\"")[0].rstrip('\n'),
			   'snr': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*snr*\"")[0].rstrip('\n'),
			   'intens': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*intens*\"")[0].rstrip('\n'),
			   'voxel_hist': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*hist*\"")[0].rstrip('\n')}
	return render(request, 'explore/stats.html', context)

def sub_register_qc(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	context = {'dataset': dataset,
			   'subject': subject,
			   'mean_anat': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*mean_anat*\"")[0].rstrip('\n'),
			   'mean_ref': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*mean_ref*\"")[0].rstrip('\n'),
			   'anat_ref': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*overall*" + subject.get_id() + "*anat_ref*\"")[0].rstrip('\n'),
			   'reg_jitter': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*reg*" + subject.get_id() + "*jitter*\"")[0].rstrip('\n'),
			   'reg_kde': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*reg*" + subject.get_id() + "*kde*\"")[0].rstrip('\n')}
	return render(request, 'explore/register.html', context)
	
def sub_nuisance_qc(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	context = {
			   'dataset':dataset,
			   'subject':subject,
			   'var': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*nuis*" + subject.get_id() + "*var*\"")[0].rstrip('\n'),
			   'er2ma': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*eroded_wm*" + subject.get_id() + "*wm_overlap*\"")[0].rstrip('\n'),
			   'ma2br': mgu().execute_cmd("find " + subject.output_url + " -wholename \"*eroded_wm*" + subject.get_id() + "*aligned_overlap*\"")[0].rstrip('\n'),
	}
	return render(request, 'explore/nuisance.html', context)

def sub_timeseries_qc(request, dataset_id, sub_id):
	dataset = get_object_or_404(Dataset, dataset_id=dataset_id)
	subject = get_object_or_404(Subject, dataset = dataset, sub_id = sub_id)
	labels = os.listdir(subject.output_url + "/roi_timeseries/")
	labelled_atlas = {}
	for label in labels:
		at2label = mgu().execute_cmd("find " + subject.output_url + " -wholename \"*roi*" + "MNI" + "*" + label + "*overlap*\"")[0].rstrip('\n')
		timeseries = mgu().execute_cmd("find " + subject.output_url + " -wholename \"*roi*" + subject.get_id() + "*" + label + "*timeseries*\"")[0].rstrip('\n')
		corr = mgu().execute_cmd("find " + subject.output_url + " -wholename \"*roi*" + subject.get_id() + "*" + label + "*cor*\"")[0].rstrip('\n')
		labelled_atlas[label] = Label_Atlas(at2label, timeseries, corr)
	context = {'dataset': dataset, 'subject': subject, 'labelled_atlas': labelled_atlas}
	return render(request, 'explore/timeseries.html', context)

class Label_Atlas:
	def __init__(self, at2label, timeseries, corr):
		self.at2label = at2label
		self.timeseries = timeseries
		self.corr = corr
		pass

fngs/explore/templates/explore/dataset.html
{% extends 'home/base.html' %}

{% block body %}
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h1 class="intro-text text-center">Analyzed Data</h1>
                <hr>
                <hr class="visible-xs">
                <p>Dataset: {{ dataset }}</p> 
                <p>Collection Site: {{ dataset.collection_site }}</p>  

                <table class="table">
                        <thead>
                        <tr>
                            <th>Subject ID</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for subject in dataset.subject_set.all %}
                            <tr>
                                <td>{{ subject.sub_id }}</td>
                                <td>
                                    <form action="{% url 'explore:sub-qc-overall' dataset.dataset_id subject.sub_id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; View
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <form action="{% url 'explore:subject-download' dataset.dataset_id subject.sub_id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-download"></span>&nbsp; Download
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
{% endblock %}

fngs/explore/templates/explore/index.html
{% extends 'home/base.html' %}

{% block body %}
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h1 class="intro-text text-center">Analyzed Datasets</h1>
                <hr>
                <hr class="visible-xs">
                {% if datasets %}
                <ul>
                    {% for dataset in datasets %}
                    <li><a href="{% url 'explore:dataset' dataset.dataset_id %}">{{ dataset.dataset_id }}</a></li>
                    {% endfor %}
                </ul>
                {% else %}
                <h3>No Datasets Available for Public Viewing.</h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

fngs/explore/templates/explore/motion.html
{% extends 'explore/subject.html' %}

{% block child %}    
<div class="row">
    <div class="box">
        <div class="col-lg-12">
            <hr>
		    <h1>Motion Correction</h1>
		    <h2>Motion Parameters</h2>
		    <p>First, we look at the motion parameters produced by mcflirt. We have both translational (x, y, and z) parameters, as well as rotational (x, y, and z) to cosider. First, we look at the rotational and translational motion parameters. Second, we consider overall motion, both absolute and relative. Absolute motion is defined as the total euclidian deviation from the zeroth timestep, whereas relative defines the distance from each timestep to its previous. Here, we want to be verifying that we do not have any sudden motions (indicated by significant spikes) as these could lead to signal dropout:</p>
		    <img src="{{ MEDIA_URL }}{{ trans }}" alt="Translational MPs" height="600" width="700">
		    <br>
		    <img src="{{ rot }}" alt="Rotational MPs" height="600" width="700">
		    <br>
		    <img src="{{ disp }}" alt="Displacement MPs" height="600" width="700">
		    <h2>Comparison Before and After Motion Correction</h2>
		    <p>We align to the zeroth slice, so what we want to look for with our preprocessing here is to compare the quality of alignment before and after motion correction to the zeroth slice of each slice in the brain. We measure similarity with the mean squared error, where a smaller error indicates that our images have better alignment of higher activation regions, which typically would be associated with high white matter alignment (for all alignment comparisons hereafter, the MSE is taken between images normalized by their maximum values, such that all intensities are normalized between 0 and 1). Below, we provide two ways to compare the alignment quality before and after motion correction; in the jitter plot, we show a single point per axial slice per time point, in the kernel density estimate, we see the distribution of mean squared errors (this distribution is over all of the points of our jitter plot). As we can see, the MSE improves slightly after motion correction, which is about what we might expect.</p>
		    <img src="{{ mcjitter }}" alt="MC jitter" height="600" width="700">
		    <img src="{{ mckde }}" alt="MC KDE" height="600" width="700">
	    </div>
	</div>
</div>

{% endblock %}

fngs/explore/templates/explore/nuisance.html
{% extends 'explore/subject.html' %}

{% block child %}    
<div class="row">
    <div class="box">
        <div class="col-lg-12">
		    <h1>Nuisance</h1>
		    <p>In these figures, we are looking to get a sense of the quality of our nuisance regression. First, we check how our eroded anatomical white matter (WM) mask aligns with the WM mask and structural brain it derives from:</p>
		    <h3>Eroded WM Mask (Deep Blue) Original WM Mask (Faint Haze)</h3>
		    <img src="{{ er2ma }}" alt="eroded mask vs wm mask" height="600" width="600">
		    <h3>Eroded WM Mask (Deep Blue) with Anatomical Brain (Faint Haze) </h3>
		    <img src="{{ ma2br }}" alt="eroded mask with brain" height="600" width="600">
		    <p>Next, we look to see the principal components estimated by Principal Component Regression of the WM signals:</p>
		    <img src="{{ var }}" alt="CompCor Variance" height="600" width="600">
	    </div>
	</div>
</div>

{% endblock %}

fngs/explore/templates/explore/overall.html
{% extends 'explore/subject.html' %}

{% block child %}    

<div class="row">
    <div class="box">
        <div class="col-lg-12">
        	<h3>Dataset</h3>
		    <p>{{ dataset.dataset_id }}</p>
		    <h3>Subject Name</h3>
		    <p>{{ subject }}</p>
		    <h3>Anatomical Resolution</h3>
		    <p>{{ res }} mm</p>
		    <h3>Temporal Resolution</h3>
		    <p>{{ tr }} sec</p>
	    </div>
	</div>
</div>

{% endblock %}

fngs/explore/templates/explore/register.html
{% extends 'explore/subject.html' %}

{% block child %}    
<div class="row">
    <div class="box">
        <div class="col-lg-12">
		    <h1>Registration</h1>
		    <p>In these figures, we are looking to get a sense of the quality of our alignment. We compare scans using one blue brain and one red brain, where any non-purple indicates failures of alignment. First, we look at the aligned fMRI image (blue) overlaid with the reference atlas (red):</p>
		    <h3>Aligned fMRI (Blue) with Atlas (Red)</h3>
		    <img src="{{ mean_ref }}" alt="Mean Atlas Overlap" height="600" width="600">
		    <h3>Aligned Structural scan (Blue) with Atlas (Red)</h3>
		    <img src="{{ anat_ref }}" alt="Mean Struct Overlap" height="600" width="600">
		    <h3>Aligned fMRI (Blue) with Structural scan (Red)</h3>
		    <img src="{{ mean_anat }}" alt="fMRI Struct Overlap" height="600" width="600">
		    <h2>Comparison Before and After Registration</h2>
		    <p>Next, we want to determine the effectiveness of our registration. Similar to the motion correction plots, we compute the axial slice-wise MSE between each axial slice per time point and that of the atlas we are registering to.</p>
		    <img src="{{ reg_jitter }}" alt="Registration jitter" height="600" width="700">
		    <img src="{{ reg_kde }}" alt="Registration KDE" height="600" width="700">
	    </div>
	</div>
</div>

{% endblock %}

fngs/explore/templates/explore/stats.html
{% extends 'explore/subject.html' %}

{% block child %}    
<div class="row">
    <div class="box">
        <div class="col-lg-12">
		    <h1>Overall</h1>
		    <h2>Summary Figures</h2>
		    <h3>Standard Deviation</h3>
		    <p>The voxelwise standard deviation over time:</p>
		    <img src="{{ std }}" alt="Voxelwise STD" height="600" width="600">

		    <h3>Mean/STD</h3>
		    <p>Next, we have the signal to noise ratio, where we define the signal to noise ratio as the quotient between the voxelwise mean and the standard deviation. Here, we generally want to have a high signal to noise ratio, as a low signal to noise ratio can often be indicative of a scanner issue or an issue running the pipeline:</p>
		    <img src="{{ snr }}" alt="Voxelwise SNR" height="600" width="600">

		    <h3>Mean Slice Intensity</h3>
		    <p>Our final few plots concern voxel statistics. First, we want to check our slice intensities. We average all of the voxels for each slice in the image, and the goal is that the average intensities are relatively consistent as we proceed in time. We show a single line for each axial slice:</p>
		    <img src="{{ intens }}" alt="fMRI Struct Overlap" height="600" width="700">

		    <h3>Histogram</h3>
		    <p>Next, we look at a histogram of voxel intensities. This distribution should appear to be relatively normal, and can sometimes take the form of a Gaussian Mixture, with one main pack of voxels (the brain intensities) and a very low number of voxels of far lower intensity (probably the skull):</p>
		    <img src="{{ voxel_hist }}" alt="fMRI Struct Overlap" height="600" width="700">
	    </div>
	</div>
</div>

{% endblock %}

fngs/explore/templates/explore/subject.html
{% extends 'home/base.html' %}

{% block body %}
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="{% url 'home:index' %}">FNGS</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'explore:sub-qc-overall' dataset.dataset_id subject.sub_id %}">Subject</a>
                    </li>                
                    <li>
                        <a href="{% url 'explore:sub-qc-motion' dataset.dataset_id subject.sub_id %}">Motion</a>
                    </li>
                    <li>
                        <a href="{% url 'explore:sub-qc-register' dataset.dataset_id subject.sub_id %}">Reg</a>
                    </li>
                    <li>
                        <a href="{% url 'explore:sub-qc-nuisance' dataset.dataset_id subject.sub_id %}">Nuis</a>
                    </li>
                    <li>
                        <a href="{% url 'explore:sub-qc-stats' dataset.dataset_id subject.sub_id %}">Stat</a>
                    </li>
                    <li>
                        <a href="{% url 'explore:sub-qc-timeseries' dataset.dataset_id subject.sub_id %}">Timeseries</a>
                    </li>
               </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- content of the quality control summary page -->
    {% block child %}
    {% endblock %}

{% endblock %}

fngs/explore/templates/explore/timeseries.html
{% extends 'explore/subject.html' %}

{% block child %}
<div class="row">
    <div class="box">
        <div class="col-lg-12">
		    <h1>Overall</h1>
		    <p>In these figures, we are looking to make sure that our brains are all in the same brain spaces. Attempting to extract timeseries if the label and the atlas are not in the same brain space could lead to disasterous results; our inferences could be impacted because regions we expect to be in particular places are not actually the correct regions in the fMRI scans, or we could extract voxels for regions that are not brain at all. We compare blue brain and one red brain, where any non-purple indicates inconsistent brain spaces (note that the rois are labelled from 1 to 70, so the lower ROIs may be quite faint in the figures). Finally, for each atlas, we show the timeseries of intensities.</p>
		    {% for label, lab in labelled_atlas.items %}
		    	<h2>{{ label }}</h2>
		    	<h3>Regitration Atlas (blue) Aligned with Labelled Atlas (red)</h3>
			    <img src="{{ lab.at2label }}" alt="Mean Label Overlap" height="600" width="600">
		    	<h3>Timeseries</h3>
			    <img src="{{ lab.timeseries }}" alt="Timeseries" height="600" width="600">
			    <h3>Correlation</h3>
			    <img src="{{ lab.corr }}" alt="Correlation Matrix" height="600" width="600">
			{% endfor %}
	    </div>
	</div>
</div>
{% endblock %}